// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class Departments
    {
        public Departments()
        {
            UserDetails = new HashSet<UserDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserDetails> UserDetails { get; set; }
    }
}