// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class ExamPapers
    {
        public ExamPapers()
        {
            ExamPaperDetails = new HashSet<ExamPaperDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? UserDetailId { get; set; }
        public DateTime? DateAdded { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<ExamPaperDetails> ExamPaperDetails { get; set; }
    }
}