// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class ExamPaperDetails
    {
        public int Id { get; set; }
        public int? ExamPaperId { get; set; }
        public int? QuestionId { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }

        public virtual ExamPapers ExamPaper { get; set; }
        public virtual Question Question { get; set; }
    }
}