// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class QuestionAnswer
    {
        public int Id { get; set; }
        public string Answer { get; set; }
        public int? QuestionId { get; set; }
        public string Choice { get; set; }
        public int? Order { get; set; }
        public string Image { get; set; }
        public bool? IsTheAnswer { get; set; }

        public virtual Question Question { get; set; }
    }
}