// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class Question
    {
        public Question()
        {
            ExamPaperDetails = new HashSet<ExamPaperDetails>();
            QuestionAnswer = new HashSet<QuestionAnswer>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string QuestionNumber { get; set; }
        public string Questions { get; set; }
        public string Choice { get; set; }
        public int? Mark { get; set; }
        public int? SubjectId { get; set; }
        public int? ExamTypeId { get; set; }
        public DateTime? Year { get; set; }
        public int? TermId { get; set; }
        public int? CreatedByUserDetailsId { get; set; }
        public DateTime? DataAdded { get; set; }
        public bool? IsDeleted { get; set; }
        public string Image { get; set; }

        public virtual UserDetails CreatedByUserDetails { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual Subjects Subject { get; set; }
        public virtual Terms Term { get; set; }
        public virtual ICollection<ExamPaperDetails> ExamPaperDetails { get; set; }
        public virtual ICollection<QuestionAnswer> QuestionAnswer { get; set; }


    }
   
}