// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuestionPool.Models
{
    public partial class Subjects
    {
        public Subjects()
        {
            Question = new HashSet<Question>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string SubjectCode { get; set; }
        public DateTime? DateCreated { get; set; }
        public string Status { get; set; }

        public virtual ICollection<Question> Question { get; set; }
    }
}