// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace QuestionPool.Models
{
    public partial class UserDetails
    {
        public UserDetails()
        {
            Question = new HashSet<Question>();
        }

        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public string Name { get; set; }

        [Display(Name = "Department")]
        public int DepartmentId { get; set; }
        public string Status { get; set; }

        public virtual Departments Department { get; set; }
        public virtual ICollection<Question> Question { get; set; }
    }
}